# Generated by Django 5.2.4 on 2025-07-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemDescription', models.TextField()),
                ('proposedArchitecture', models.TextField()),
                ('designTradeoffs', models.TextField()),
                ('scalibilty', models.TextField()),
                ('securityMeasures', models.TextField()),
                ('maintainability', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Incomplete', 'Incomplete'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('submissionDate', models.DateTimeField(auto_now_add=True)),
                ('overallScore', models.IntegerField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_reviews', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='DesignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProcessed', models.CharField(choices=[('error', 'Error'), ('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10)),
                ('path', models.FileField(upload_to='design_documents/')),
                ('type', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('designReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.designreview')),
            ],
        ),
        migrations.CreateModel(
            name='DesignReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallscore', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Incomplete', 'Incomplete'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('reviewedOn', models.DateTimeField()),
                ('technicalDepth', models.IntegerField()),
                ('systemDesign', models.IntegerField()),
                ('tradeoff', models.IntegerField()),
                ('ownership', models.IntegerField()),
                ('feedbackSummary', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('designReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.designreview')),
            ],
        ),
        migrations.CreateModel(
            name='ProbingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('designReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probing_questions', to='api.designreview')),
            ],
        ),
    ]
