# Generated by Django 5.2.4 on 2025-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_designdocument_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='isProcessed',
            field=models.CharField(choices=[('error', 'Error'), ('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('done', 'Done')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='designreview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Incomplete', 'Incomplete'), ('Completed', 'Completed'), ('Questions Generated', 'Questions Generated'), ('In Progress', 'In Progress'), ('Reviewed', 'Reviewed'), ('Finalized', 'Finalized')], default='Pending', max_length=20),
        ),
    ]
